### ISSUE TITLE
Docker built. Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache()

### ISSUE THREAD

**Issue by mgyong** [figroc/tensorflow-serving-client#11]
I built the docker container to generate Golang TF serving client. 

Having error below 
```
Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache().
   > Failed to create parent directory '/work/.gradle' when creating directory '/work/.gradle/6.5.1/fileHashes'

```
```
mgyong@instance-2:~/code/tensorflow-serving-client$ docker logs tsc

Welcome to Gradle 6.5.1!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache().
   > Failed to create parent directory '/work/.gradle' when creating directory '/work/.gradle/6.5.1/fileHashes'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not create service of type CrossBuildFileHashCache using BuildSessionServices.createCrossBuildFileHashCache().
   > Failed to create parent directory '/work/.gradle' when creating directory '/work/.gradle/6.5.1/fileHashes'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

**Comment by figroc** [comment]
It seems like a permission issue. 🤔

**Comment by mgyong** [comment]
I am just running your Dockerfile in the repo. How can we solve this permission issue?

**Comment by figroc** [comment]
I'm working on it.

**Comment by figroc** [comment]
I've run several builds on a fresh installed Ubuntu 18.04 VM. All builds go well. 

The building container runs as the user gradle(1000). The UID of host user is also 1000 in my builds. They map each other perfectly which makes the permission good to go.

Here is what I think would be a workaround of the issue you encountered:
1. Create a user account with UID 1000 and GID 1000.
2. Add the user to the group which your current user belongs to.
3. Add write permission for your group to `.gradle` and `build` in the repo dir, recursively.

**Comment by mgyong** [comment]
Is there a reason you need to have [line 54](https://github.com/figroc/tensorflow-serving-client/blob/master/Dockerfile#L54) `USER Gradle`
Why can't we remove line 54 and get around the permission issue ?

**Comment by figroc** [comment]
There would be 2 issues if the container ran as `root`.
1. The generated files would be `root` owned. I personally don't like it.
2. The build tools would need more env configurations. I did have managed to fix them. But it was tedious.

I'm still digging around trying to work around the user mapping issue without compromise the ownership.

**Comment by mgyong** [comment]
Removed line54 and was able to do `gradle golang` and get it working.

Question: I see lib.go and the go.mod in the generated folder. How do you go about using the lib.go?

<img width="277" alt="Screen Shot 2020-07-24 at 6 01 08 PM" src="https://user-images.githubusercontent.com/2178001/88445474-b5347c80-cdd7-11ea-8337-554184bf3193.png">

**Comment by figroc** [comment]
It actually is useless here. Does it break anything?

**Comment by mgyong** [comment]
No i am trying to figure out how to use the generated protobuf in a grpc client in gollang. Do you have code example of how to incorporate the generated protobuf files?

**Comment by figroc** [comment]
I'm working on the tests.

**Comment by mgyong** [comment]
Any update on code example on how to use the generated protobuf files?

**Comment by figroc** [comment]
There is no good way to change the uid of the container user in a consistent way. One can change the `build.sh` script if needed. I would close the issue for now.
