### ISSUE TITLE
Having issue with "tensorflow/core/framework"

### ISSUE THREAD

**Issue by mgyong** [figroc/tensorflow-serving-client#13]
i was able to run `gradle golang` and generate golang protobufs
When i try to use the generated golang protobufs for `"tensorflow/core/framework"` as show in the public repo code below
[https://github.com/mgyong/tensorflow-serving-client-go/blob/master/main.go#L12](https://github.com/mgyong/tensorflow-serving-client-go/blob/master/main.go#L12)

When i try to run `go build main.go` I get the below error message

`main.go:12:2: module tensorflow@latest found (v0.0.0-00010101000000-000000000000, replaced by ./tensorflow), but does not contain package tensorflow/core/framework
`
However `pb "tensorflow_serving/apis"` seems to work and not provide errors

**Comment by figroc** [comment]
Since `r2.2`, the package hierarch of pbs from tensorflow has been changed. Every pb file under `tensorflow/core/framework` is generated under each own package name. And the importing has to change accordingly:

```diff
-       tf_core_framework "tensorflow/core/framework"
+       tf_core_types "tensorflow/core/framework/types_go_proto"
+       tf_core_tensor "tensorflow/core/framework/tensor_go_proto"
+       tf_core_shape "tensorflow/core/framework/tensor_shape_go_proto"
```
